services:
  attacker:
    image: c4pr1c3/crs-base
    command: sh -c "httpd -DFOREGROUND"
    networks:
      - outer
  gw:
    image: c4pr1c3/crs-base
    command: sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward && iptables -t nat -A POSTROUTING -s ${VICTIM_NET_RANGE} -j MASQUERADE && iptables -t nat -A POSTROUTING -s ${VICTIM_NET_1_RANGE} -j MASQUERADE && iptables -t nat -A POSTROUTING -s ${VICTIM_NET_2_RANGE} -j MASQUERADE && iptables -t nat -A POSTROUTING -s ${VICTIM_NET_3_RANGE} -j MASQUERADE && tcpdump -i inner-0 -n & tcpdump -i v1-0 -n & tcpdump -i v2-0 -n & tcpdump -i v3-0 -n & tail -f /dev/null"
    cap_add:
      - net_admin
      - net_raw
    networks:
      outer:
        ipv4_address: "${GW_OUTER_IP}"
      inner:
        ipv4_address: "${GW_INNER_IP}"
        ipv6_address: "2001:3984:3989::3"
      victim-net-1:
        ipv4_address: "${GW_VICTIM_1_IP}"
      victim-net-2:
        ipv4_address: "${GW_VICTIM_2_IP}"
      victim-net-3:
        ipv4_address: "${GW_VICTIM_3_IP}"
  victim-1:
    image: c4pr1c3/crs-base
    command: sh -c "ip r delete default via ${INNER_GW_IP} && ip r add default via ${GW_INNER_IP} && httpd -DFOREGROUND"
    cap_add:
      - net_admin
      - net_raw
    networks:
      inner:
        ipv4_address: "${V1_IP}"
        ipv6_address: "2001:3984:3989::101"
  victim-2:
    image: c4pr1c3/crs-base
    command: sh -c "ip r delete default via ${INNER_GW_IP} && ip r add default via ${GW_INNER_IP} && httpd -DFOREGROUND"
    cap_add:
      - net_admin
      - net_raw
    networks:
      inner:
        ipv4_address: "${V2_IP}"
        ipv6_address: "2001:3984:3989::102"
  victim-net-1:
    build:
      context: ./docker/crs-min
    command: sh -c "ip r del default via ${VICTIM_NET_1_GW} || true; ip r add default via ${GW_VICTIM_1_IP}; tail -f /dev/null"
    cap_add:
      - net_admin
      - net_raw
    networks:
      - victim-net-1
  victim-net-2:
    build:
      context: ./docker/crs-min
    command: sh -c "ip r del default via ${VICTIM_NET_2_GW} || true; ip r add default via ${GW_VICTIM_2_IP}; tail -f /dev/null"
    cap_add:
      - net_admin
      - net_raw
    networks:
      - victim-net-2
  victim-net-3:
    build:
      context: ./docker/crs-min
    command: sh -c "ip r del default via ${VICTIM_NET_3_GW} || true; ip r add default via ${GW_VICTIM_3_IP}; tail -f /dev/null"
    cap_add:
      - net_admin
      - net_raw
    networks:
      - victim-net-3

networks:
  inner:
    # use the bridge driver, but enable IPv6
    driver: bridge
    internal: false
    # ref: https://docs.docker.com/engine/reference/commandline/network_create/#bridge-driver-options
    driver_opts:
        com.docker.network.enable_ipv6: "true"
        com.docker.network.bridge.name:  "inner"
        com.docker.network.container_iface_prefix: "inner-"
    ipam:
      driver: default
      config:
        - subnet: ${VICTIM_NET_RANGE}
          gateway: ${INNER_GW_IP}
        - subnet: "2001:3984:3989::/64"
          gateway: "2001:3984:3989::1"
  outer:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv6: "false"
        com.docker.network.bridge.name:  "outer"
        com.docker.network.container_iface_prefix: "outer-"
    ipam:
      driver: default
      config:
        - subnet: ${OUTER_NET_RANGE}
          gateway: ${OUTER_GW_IP}
  victim-net-1:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv6: "false"
        com.docker.network.bridge.name:  "victim-net-1"
        com.docker.network.container_iface_prefix: "v1-"
    ipam:
      driver: default
      config:
        - subnet: ${VICTIM_NET_1_RANGE}
          gateway: ${VICTIM_NET_1_GW}
  victim-net-2:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv6: "false"
        com.docker.network.bridge.name:  "victim-net-2"
        com.docker.network.container_iface_prefix: "v2-"
    ipam:
      driver: default
      config:
        - subnet: ${VICTIM_NET_2_RANGE}
          gateway: ${VICTIM_NET_2_GW}
  victim-net-3:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv6: "false"
        com.docker.network.bridge.name:  "victim-net-3"
        com.docker.network.container_iface_prefix: "v3-"
    ipam:
      driver: default
      config:
        - subnet: ${VICTIM_NET_3_RANGE}
          gateway: ${VICTIM_NET_3_GW}
